### ISSUE TITLE
Problems with building biliography

### ISSUE THREAD

**Issue by MartinJakomin** [UL-FRI/thesis-BDR#17]
Sometimes when I try to build my thesis, the build fails:

> 
> Latexmk: Summary of warnings from last run of (pdf)latex:
>   Latex failed to resolve 58 reference(s)
>   Latex failed to resolve 186 citation(s)
> Latexmk: Errors, so I did not complete making targets
> Latexmk: Use the -f option to force complete processing,
>  unless error was exceeding maximum runs, or warnings treated as errors.

This problem is resolved if I run the build 2 additional times or if I run:

> ../editor-cfg/build; ../editor-cfg/build; ../editor-cfg/build

**Comment by itzsimpl** [comment]
Can you provide a MWE to recreate the error?

In addition you say sometimes. So what changes have you made since the last time you built in a single run (without failure)? What changes do not lead to failure? Do your filenames, paths include spaces? Have you tried compiling with `latexmk -f` (this will build the thesis in the stage listed when loading the class, ../editor-cfg/build is just a helper)?

**Comment by MartinJakomin** [comment]
The issue was in too many bibtex warnings. After resolving all warnings (missing journals, missing booktitles, etc.) and thus lowering the amount of overall warnings the build runs just fine (with one sole run). Still, warnings should not cause build errors.
