### ISSUE TITLE
Magic comments instead of settings for VScode?

### ISSUE THREAD

**Issue by gw0** [UL-FRI/thesis-BDR#8]
Currently examples contain `.vscode/settings.json` with configuration specific for LaTeX-Workshop for VScode. Recently they added support for additional magic commands ([issue](https://github.com/James-Yu/LaTeX-Workshop/issues/484#issuecomment-460980069), [docs](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#magic-comments)) similar to what is supported by [LaTeXTools for Sublime Text](https://latextools.readthedocs.io/en/latest/features/#tex-options).

For VScode it is now sufficient to add the following magic comments in the header of `thesis.tex`:

```
% !TEX program = xelatex
% !TEX options = -aux-directory=./int -include-directory=./FRIteza -include-directory=./int -output-directory=./out -synctex=1 -interaction=nonstopmode -file-line-error "%DOC%"
% !BIB program = bibtex
% !BIB options = -include-directory=./FRIteza "./int/%DOCFILE%"
```

Unfortunately, the crucial `!TEX options` and `!BIB options` are not widely supported (`!TEX program` and `!BIB program` are). I am not sure how meaningful is it to replace current VScode configuration with these magic comments until support becomes wider (maybe we could send PRs or open issues for all major editors and tools?).

**Comment by itzsimpl** [comment]
As you are probably aware the FRIthesis template is designed to follow the five stages of a doctoral dissertation. Each one influences the generated PDF slightly. As of this moment the magic commands do not provide the tools to solve the stage building process in an elegant way, especially since in the press stage one needs to build both `thesis.tex` and `cover.tex`. In the latest commit 07032ab in the [[WIP] add_stage_parameter](https://github.com/UL-FRI/thesis-BDR/tree/add_stage_parameter) branch a special build script is provided to generate the corresponding PDF, depending on the chosen stage. We are currently working on a solution that would be as similar as possible, regardless of the IDE or lack of it (command line, TeXStudio, VScode or Overleaf). 

Currently only VScode with the possibility to define specific LaTeX recipes via `.vscode/settings.json` provides the best tools to have individual recipes for individual stages of the doctoral dissertation. If, however, one chooses to manually specify the stage (by passing the corresponding stage parameter when loading the FRIthesis class file), one could remove the `.vscode` folder altogether and instead use the [latexmk](https://mg.readthedocs.io/latexmk.html) build script. In this case the configuration is specified via a `latexmkrc` or `.latexmkrc` file which contains:
```
$ENV{'TEXINPUTS'}='../:./int/:./out/:';
$ENV{'BSTINPUTS'}='../:./int/:./out/:';
$ENV{'OPENTYPEFONTS'}='.:../:';
$ENV{'TTFONTS'}='.:../:';

$bibtex_fudge=0;

$pdf_mode=1;
$pdflatex="xelatex %O %S";

$out_dir = "./out";
$aux_dir = "./int";
@default_files = ('thesis.tex', 'cover.tex');
```
Note that this requires MikTeX (support for `$aux_dir`). By using this config file one can simply build with the default compile recipe, which in VScode is `latexmk` anyway (default also for Overleaf). As a plus, the command line build is executed just by typing:
```
$ latexmk thesis
``` 
Note that in this case the stage needs to be set in `thesis.tex` when loading the FRIthesis class. Another possible toolchain might be `latexjs`, see James-Yu/LaTeX-Workshop#119, which due to time constraints remains untested.

Sending PRs or open issues on all major editors is an idea, but it probably should be such that it will allow for the definition of stage dependant recipes.

**Comment by itzsimpl** [comment]
[FRIteza v2.20190301](
https://github.com/UL-FRI/thesis-BDR/releases/tag/v2.20190301) supports  VScode with LaTeX-Workshop via LaTeX recipes. A configuration for TeXstudio is also provided. Both are based on the [latexmk](https://mg.readthedocs.io/latexmk.html) build script. In addition a script is provided to pack all the required files into a single zip to be uploaded to Overleaf. See README.md for further details. Due to time constraints we do not plan to provide support for other IDEs (e.g. Sublime Text).

**Comment by gw0** [comment]
Thanks, `latexmk` with stages seems to be the most elegant solution.

If you instead manually specify the stage, this also works with VSCode:

```
% !TEX program = latexmk
\documentclass[language=english,stage=beta]{FRIteza}
```
